let imageArray = [{
   label: 'StartScreen',
   src: '../CatDog/images/StartScreen.png'
}, {
  label: 'Player1Wins',
  src: '../CatDog/images/Player1Wins.png'
}, {
  label: 'Player2Wins',
  src: '../CatDog/images/Player2Wins.png'
}, {
  label: 'CatDeadLeft',
  src: '../CatDog/images/cat-dog-tileset/CatDeadLeft.png'
}, {
  label: 'CatDeadRight',
  src: '../CatDog/images/cat-dog-tileset/CatDeadRight.png'
}, {
  label: 'CatFallLeft',
  src: '../CatDog/images/cat-dog-tileset/CatFallLeft.png'
}, {
  label: 'CatFallRight',
  src: '../CatDog/images/cat-dog-tileset/CatFallRight.png'
}, {
  label: 'CatIdleLeft',
  src: '../CatDog/images/cat-dog-tileset/CatIdleLeft.png'
}, {
  label: 'CatIdleRight',
  src: '../CatDog/images/cat-dog-tileset/CatIdleRight.png'
}, {
  label: 'CatJumpLeft',
  src: '../CatDog/images/cat-dog-tileset/CatJumpLeft.png'
}, {
  label: 'CatJumpRight',
  src: '../CatDog/images/cat-dog-tileset/CatJumpRight.png'
}, {
  label: 'CatRunLeft',
  src: '../CatDog/images/cat-dog-tileset/CatRunLeft.png'
}, {
  label: 'CatRunRight',
  src: '../CatDog/images/cat-dog-tileset/CatRunRight.png'
}, {
  label: 'CatStunnedLeft',
  src: '../CatDog/images/cat-dog-tileset/CatStunnedLeft.png'
}, {
  label: 'CatStunnedRight',
  src: '../CatDog/images/cat-dog-tileset/CatStunnedRight.png'
}, {
  label: 'DogDeadLeft',
  src: '../CatDog/images/cat-dog-tileset/DogDeadLeft.png'
}, {
  label: 'DogDeadRight',
  src: '../CatDog/images/cat-dog-tileset/DogDeadRight.png'
}, {
  label: 'DogFallLeft',
  src: '../CatDog/images/cat-dog-tileset/DogFallLeft.png'
}, {
  label: 'DogFallRight',
  src: '../CatDog/images/cat-dog-tileset/DogFallRight.png'
}, {
  label: 'DogIdleLeft',
  src: '../CatDog/images/cat-dog-tileset/DogIdleLeft.png'
}, {
  label: 'DogIdleRight',
  src: '../CatDog/images/cat-dog-tileset/DogIdleRight.png'
}, {
  label: 'DogJumpLeft',
  src: '../CatDog/images/cat-dog-tileset/DogJumpLeft.png'
}, {
  label: 'DogJumpRight',
  src: '../CatDog/images/cat-dog-tileset/DogJumpRight.png'
}, {
  label: 'DogRunLeft',
  src: '../CatDog/images/cat-dog-tileset/DogRunLeft.png'
}, {
  label: 'DogRunRight',
  src: '../CatDog/images/cat-dog-tileset/DogRunRight.png'
}, {
  label: 'DogStunnedLeft',
  src: '../CatDog/images/cat-dog-tileset/DogStunnedLeft.png'
}, {
  label: 'DogStunnedRight',
  src: '../CatDog/images/cat-dog-tileset/DogStunnedRight.png'
}, {
  label: 'tennisBall',
  src: '../CatDog/images/cat-dog-tileset/tennisBall.png'
}, {
  label: 'yarnBall',
  src: '../CatDog/images/cat-dog-tileset/yarnBall.png'
}];

let soundArray = [{
    label: 'happyMusic',
    src: '../audio/happy.mp3'
}, {
    label: 'loadingLoop',
    src: '../audio/loading-loop-0.wav'
}, {
  label: 'theLastEncounterExtended',
  src: '../audio/tle-extended.mp3'
}];

export { imageArray, soundArray }
